default_inputs:
    clean_workdir: False
    kpoints_distance: 0.15
    kpoints_force_parity: False
    max_iterations: 5
    meta_parameters:
        conv_thr_per_atom: 0.2e-9
        etot_conv_thr_per_atom: 1.e-5
    pseudo_family: 'SSSP/1.3/PBE/precision'
    pw:
        metadata:
            options:
                resources:
                    tot_num_mpiprocs: 1
                max_wallclock_seconds: 43200  # Twelve hours
                withmpi: True
        parameters:
            CONTROL:
                calculation: scf
                forc_conv_thr: 1.e-4
                tprnfor: True
                tstress: True
            SYSTEM:
                nosym: False
                occupations: smearing
                smearing: cold
                degauss: 0.01
            ELECTRONS:
                electron_maxstep: 80
                mixing_beta: 0.4
    environ:
        parameters:
            ENVIRON:
                env_electrostatic: True
                env_confine: 0.0
                environ_restart: False
                env_static_permittivity: 78.3
                env_pressure: -0.35
                env_surface_tension: 50
                verbose: 1
                environ_thr: 100
            BOUNDARY: 
                alpha: 1.12
                radius_mode: 'muff'
                solvent_mode: 'ionic'
                field_aware: True
                field_factor: 0.24
                field_asymmetry: 0.32
                field_max: 6
                field_min: 2
                deriv_method: 'lowmem'
            ELECTROSTATIC: 
                auxiliary: 'none'
                pbc_correction: 'parabolic'
                pbc_dim: 0
                solver: 'cg'
                tol: 1.E-10
default_protocol: moderate
protocols:
    moderate:
        description: 'Protocol to perform the computation at normal precision at moderate computational cost.'
    precise:
        description: 'Protocol to perform the computation at high precision at higher computational cost.'
        kpoints_distance: 0.10
        meta_parameters:
            conv_thr_per_atom: 0.1e-9
            etot_conv_thr_per_atom: 0.5e-5
        pseudo_family: 'SSSP/1.2/PBEsol/precision'
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 0.5e-4
    fast:
        description: 'Protocol to perform the computation at low precision at minimal computational cost for testing purposes.'
        kpoints_distance: 0.50
        meta_parameters:
            conv_thr_per_atom: 0.4e-9
            etot_conv_thr_per_atom: 1.e-4
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 1.e-3